spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

ai:
  server:
    url: ${PROD_AI_SERVER_URL}

app:
  storage:
    local-path: ${PROD_STORAGE_PATH:/data/uploads/}
    base-url: ${PROD_APP_BASE_URL}/uploads/


