spring:
  datasource:
    url: jdbc:h2:mem:narae;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true

ai:
  server:
    url: http://localhost:8000
